name: hesapkontrol
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  table_calendar: ^3.1.1
  barcode_scan2: ^4.3.0
  firebase_core: ^2.31.1
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.20.0
  http: ^1.2.1
  html: ^0.15.4
  intl: ^0.19.0
  pdf: ^3.10.8
  path_provider: ^2.1.3
  open_file: ^3.3.2
  permission_handler: ^11.3.1
  google_fonts: ^6.2.1
  file_picker: ^8.0.3
  flutter_isolate: ^2.0.4
  provider: ^6.1.2
  shared_preferences: ^2.0.8
  printing: ^5.13.1
  excel: ^4.0.3
  syncfusion_flutter_xlsio: ^26.1.41

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf