// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqtOgorUIYpP8MoUAnuCeGDZ_df_4DCzY',
    appId: '1:525820897685:web:8dff576a1a7abb843dee9c',
    messagingSenderId: '525820897685',
    projectId: 'veritabani-c4fea',
    authDomain: 'veritabani-c4fea.firebaseapp.com',
    storageBucket: 'veritabani-c4fea.appspot.com',
    measurementId: 'G-WYZ8HCEZ3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWlkFHmw39ySAoJv2dJTFs3CdPuwV9QBY',
    appId: '1:525820897685:android:1e933c77241ad7223dee9c',
    messagingSenderId: '525820897685',
    projectId: 'veritabani-c4fea',
    storageBucket: 'veritabani-c4fea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc04I0d2r1rAUTMIRA-0tHjwtPxJJ3CF0',
    appId: '1:525820897685:ios:515a8d1bde49348c3dee9c',
    messagingSenderId: '525820897685',
    projectId: 'veritabani-c4fea',
    storageBucket: 'veritabani-c4fea.appspot.com',
    iosBundleId: 'com.example.defter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc04I0d2r1rAUTMIRA-0tHjwtPxJJ3CF0',
    appId: '1:525820897685:ios:515a8d1bde49348c3dee9c',
    messagingSenderId: '525820897685',
    projectId: 'veritabani-c4fea',
    storageBucket: 'veritabani-c4fea.appspot.com',
    iosBundleId: 'com.example.defter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqtOgorUIYpP8MoUAnuCeGDZ_df_4DCzY',
    appId: '1:525820897685:web:dfca5a6c453116303dee9c',
    messagingSenderId: '525820897685',
    projectId: 'veritabani-c4fea',
    authDomain: 'veritabani-c4fea.firebaseapp.com',
    storageBucket: 'veritabani-c4fea.appspot.com',
    measurementId: 'G-GLBMDL8CQK',
  );
}
